### ISSUE TITLE
是否支持第三方键盘

### ISSUE THREAD

**Issue by ShaochongDu** [ibireme/YYKeyboardManager#3]

**Comment by ibireme** [comment]
滋词

**Comment by ShaochongDu** [comment]
![pic](https://cloud.githubusercontent.com/assets/16948310/14661581/4c7f63c4-06e1-11e6-9029-635e3a671459.png)

搜狗输入法 有时候会出现上边的情况，不知道为什么。

**Comment by ibireme** [comment]
这个监听的都是系统事件，与输入法无关的。。
贴一下你的代码看看。

**Comment by ShaochongDu** [comment]
我看打印了一个这个，是不是你代码里打印的：
plugin com.sogou.sogouinput.basekeyboard invalidated

**Comment by ibireme** [comment]
不是啊，这里面并没有 log，也没有针对不同键盘进行多余的处理。

**Comment by ShaochongDu** [comment]
原因找到了，是跟我用的一个类目处理键盘的时候冲突了。请问你这个如果要是一个页面上有多个textview或textfield 有简单点的方式处理吗

**Comment by ibireme** [comment]
这个 Manager 类，只是很简单的提供了监听键盘位置和动画、访问键盘视图的功能，并没有额外的东西。

如果你只需要处理与 TextView/TextField 之类的交互处理，而不关心键盘操作，建议试试 IQKeyboardManager。

**Comment by ShaochongDu** [comment]
恩  好的 多谢

**Comment by AgentEric** [comment]
使用百度输入法的时候   
 YYTextKeyboardManager *manager = [YYTextKeyboardManager defaultManager];
    CGRect toFrame =  [manager convertRect:transition.toFrame toView:self.view];
    BOOL fromVisible = transition.fromVisible;
    BOOL toVisible = transition.toVisible;
toFrame 的高度只有216，百度输入法上面还有一个类似 toolbar 的控件
