### ISSUE TITLE
我发现在iOS7时keyboardmanager  的isKeyboardVisible状态是不对的

### ISSUE THREAD

**Issue by d1248966459** [ibireme/YYKeyboardManager#4]

**Comment by ibireme** [comment]
能描述一些具体的情况吗？

比如真机还是模拟器，iPad 还是 iPhone，连没连键盘，相关代码？

**Comment by d1248966459** [comment]
真机 ipad 还有iphone 都是一样的，跑的是demo，调试发现获得的keyboardView为nil，还在进一步找具体原因

**Comment by ibireme** [comment]
我有一台未越狱的 iPad 7.1.2，测试是没问题的。。

**Comment by d1248966459** [comment]
状态么？我在iphone4 7.1.2上跑的demo效果是对的 但是状态是不对的

**Comment by ibireme** [comment]
如果效果是正确的，那状态应该也没问题。。
注意一下调用时机和动画。

**Comment by d1248966459** [comment]
![05fbfe5e-e3f1-43ec-9f04-eef4eab23135](https://cloud.githubusercontent.com/assets/10206647/14706748/166a4c78-07f3-11e6-8ca4-280e0df6c6f1.png)
![screen shot 2016-04-21 at 6 49 27](https://cloud.githubusercontent.com/assets/10206647/14706756/1f23fc42-07f3-11e6-9a45-d0d3646c3364.png)

**Comment by d1248966459** [comment]
这是显示的效果和状态

**Comment by ibireme** [comment]
这是一个 transition 的中间状态，这个回调中应该取 transition.fromVisible 和 transition.toVisible 这两个值来判断 transition 前后的键盘状态。。

**Comment by d1248966459** [comment]
测试过了 谢大神啦！
