### ISSUE TITLE
对这个判断有点疑问

### ISSUE THREAD

**Issue by ColinHwang** [ibireme/YYKeyboardManager#8]
你好，看源码时，对_getKeyboardViewFromWindow:方法的判断有点疑问：

```
// UITextEffectsWindow
if (windowName.length != 19) return nil;
if (![windowName hasPrefix:@"UI"]) return nil;
if (![windowName hasSuffix:@"TextEffectsWindow"]) return nil;
```

为何不用：
`if (![windowName isEqualToString:@"UITextEffectsWindow"]) return nil;`

这两种判断有什么区别吗？

**Comment by ibireme** [comment]
逻辑上没区别。

只是 UITextEffectsWindow 是一个 private class，所以最开始不太敢直接写在这里（实际上直接写可能也是没问题的）。

**Comment by ColinHwang** [comment]
原来如此，感谢回复。
